# Generated by Django 4.0.6 on 2022-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('task_completed', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
            ],
            options={
                'db_table': 'zadacha',
            },
        ),
    ]
